[common]
version = 0.6.0
build_flags =
    -DVERSION=\"LaskaKit-${common.version}\"
    -D${sysenv.DISPLAY_TYPE}
    -DCORE_DEBUG_LEVEL=3  ; 0-none, 1-error, 2-warn, 3-info, 4-debug, 5-verbose
    -std=gnu++17
build_unflags =
    -std=gnu++11
lib_deps_gxepd =
    https://github.com/ZinggJM/GxEPD2.git ; more displays available
    https://github.com/ZinggJM/GxEPD2_4G
lib_deps_bb =
    bitbank2/bb_epaper@^2.1.9
lib_deps_fastepd =
    bitbank2/FastEPD@^1.4.6
lib_deps_sensor =
    adafruit/Adafruit SHT4x Library@^1.0.5
    adafruit/Adafruit BME280 Library@^2.3.0
    sparkfun/SparkFun SCD4x Arduino Library@^1.1.2
    sensirion/Sensirion I2C STCC4@^1.0.0
    sensirion/Sensirion I2C SGP41@^1.0.0
    claws/BH1750@^1.3.0

[env]
framework = arduino
platform = espressif32@6.11
monitor_speed = 115200
upload_speed = 460800
build_flags = ${common.build_flags}
build_unflags = ${common.build_unflags}
lib_deps =
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.4.2
    adafruit/Adafruit GFX Library@^1.12.4
    ${common.lib_deps_sensor}
extra_scripts = merge_firmware.py
monitor_filters = esp32_exception_decoder

[env:espink-v3]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi ; OPI PSRAM + QIO Flash
board_build.psram_type = opi              ; OPI PSRAM mode
build_flags =
    ${common.build_flags}
	-DESPINK_V3
	; -DBOARD_HAS_PSRAM
lib_deps:
    ${env.lib_deps}

[env:espink-v3-gxepd]
extends = env:espink-v3
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_gxepd}

[env:espink-v3-bbep]
extends = env:espink-v3
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_bb}

[env:uespink-v1]
board = esp32-s3-devkitc-1
build_flags =
    ${common.build_flags}
    -DUESPINK_V1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}

[env:uespink-v1-gxepd]
extends = env:uespink-v1
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_gxepd}

[env:uespink-v1-bbep]
extends = env:uespink-v1
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_bb}

[env:espink-v2]
board = esp32dev
build_flags =
    ${common.build_flags}
    -DESPINK_V2
lib_deps =
    ${env.lib_deps}

[env:espink-v2-gxepd]
extends = env:espink-v2
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_gxepd}

[env:epdiy-v7-fastepd]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi ; OPI PSRAM + QIO Flash
board_build.psram_type = opi              ; OPI PSRAM mode
build_flags =
    ${common.build_flags}
    -DEPDIY_V7
    -DBOARD_HAS_PSRAM
lib_deps =
    ${env.lib_deps}
    ${common.lib_deps_fastepd}
