name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Use cache 
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build all firmware
      run: pio run
    
    - name: Prepare release artifacts
      run: |
        mkdir -p release/
        cp .pio/build/*/firmware.bin release/
        cp .pio/build/*/firmware_merged.bin release/
        # Rename files to include environment name
        for env in espink_v2-6 espink_v3-5; do
          if [ -f ".pio/build/$env/firmware.bin" ]; then
            cp ".pio/build/$env/firmware.bin" "release/${env}-firmware.bin"
          fi
          if [ -f ".pio/build/$env/firmware_merged.bin" ]; then
            cp ".pio/build/$env/firmware_merged.bin" "release/${env}-firmware_merged.bin"
          fi
        done
        ls -la release/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true
        draft: true
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
